"use client";

import { useState } from "react";
import { ChatPanel } from "./ChatPanel";
import { ContextPanel } from "./ContextPanel";
import { WorkflowSidebar } from "./WorkflowSidebar";

// MVP workspace ID - no auth for hackathon
const MVP_WORKSPACE_ID = "00000000-0000-4000-8000-000000000001";

const defaultBobPrompt = `Inspect repository context.

Mission:
Implement ADA QA Gate.

Constraints:
- Next.js App Router
- TypeScript
- Tailwind
- No unrelated changes
- Provide changed files
- Provide validation evidence`;

const defaultReadinessItems: Array<[string, boolean]> = [
  ["Mission structured", true],
  ["Planning gate created", true],
  ["Bob prompt ready", true],
  ["QA review complete", false],
  ["Evidence exported", false],
];

export function AdaCockpit() {
  const [currentMission] = useState({
    title: "QA Gate",
    description:
      "Review Bob implementation output against mission scope, acceptance criteria, risks, and release readiness.",
  });

  const [bobPrompt, setBobPrompt] = useState(defaultBobPrompt);
  const [readinessItems, setReadinessItems] = useState(defaultReadinessItems);

  const handleBobPromptDetected = (prompt: string) => {
    setBobPrompt(prompt);
    // Update readiness when Bob prompt is generated
    setReadinessItems((prev) =>
      prev.map(([label, status]) =>
        label === "Bob prompt ready" ? [label, true] : [label, status]
      )
    );
  };

  const handleExportMarkdown = () => {
    // Generate markdown export of current delivery state
    const timestamp = new Date().toISOString();
    const markdown = `# ADA Delivery Report
Generated: ${timestamp}

## Current Mission
**${currentMission.title}**

${currentMission.description}

## Bob Prompt Preview
\`\`\`
${bobPrompt}
\`\`\`

## Readiness Checklist
${readinessItems
  .map(([label, status]) => `- [${status ? "x" : " "}] ${label}`)
  .join("\n")}

## Release Gate Status
Commit and push only after QA acceptance, evidence export, and human approval.

---
*Generated by ADA — AI Delivery Architect*
*Workspace: ${MVP_WORKSPACE_ID}*
`;

    // Create and download markdown file
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ada-delivery-report-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Update readiness
    setReadinessItems((prev) =>
      prev.map(([label, status]) =>
        label === "Evidence exported" ? [label, true] : [label, status]
      )
    );
  };

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100">
      <header className="border-b border-neutral-800 bg-neutral-950/95 px-6 py-5">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-6">
          <div>
            <p className="font-mono text-xs uppercase tracking-[0.3em] text-blue-400">
              IBM Bob Workflow Companion
            </p>
            <h1 className="mt-2 text-4xl font-black tracking-tight md:text-6xl">
              ADA — AI Delivery Architect
            </h1>
            <p className="mt-3 max-w-2xl text-sm text-neutral-400">
              Bob builds. Ada orchestrates and reviews. You lead.
            </p>
          </div>
          <div className="hidden border border-blue-500 bg-blue-500/10 px-4 py-3 font-mono text-xs uppercase tracking-[0.2em] text-blue-300 md:block">
            Two AIs are better than one
          </div>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-4 px-6 py-6 lg:grid-cols-[260px_1fr_360px]">
        <WorkflowSidebar />

        <ChatPanel
          workspaceId={MVP_WORKSPACE_ID}
          onBobPromptDetected={handleBobPromptDetected}
        />

        <ContextPanel
          currentMission={currentMission}
          bobPrompt={bobPrompt}
          readinessItems={readinessItems}
          onExportMarkdown={handleExportMarkdown}
        />
      </section>
    </main>
  );
}

// Made with Bob
