"use client";

import { useState } from "react";
import { ChatPanel } from "./ChatPanel";
import { ContextPanel } from "./ContextPanel";
import { WorkflowSidebar } from "./WorkflowSidebar";

// MVP workspace ID - no auth for hackathon
const MVP_WORKSPACE_ID = "00000000-0000-4000-8000-000000000001";

const defaultBobPrompt = `Inspect repository context.

Mission:
Implement ADA QA Gate.

Constraints:
- Next.js App Router
- TypeScript
- Tailwind
- No unrelated changes
- Provide changed files
- Provide validation evidence`;

const defaultReadinessItems: Array<[string, boolean]> = [
  ["Mission structured", true],
  ["Planning gate created", true],
  ["Bob prompt ready", false],
  ["QA review complete", false],
  ["Evidence exported", false],
];

export function AdaCockpit() {
  const [currentMission] = useState({
    title: "ADA Active Mission",
    description:
      "Chat-first delivery control cockpit connected to ADA memory, Bob prompt preview, readiness checklist, and release gate workflow.",
  });

  const [bobPrompt, setBobPrompt] = useState(defaultBobPrompt);
  const [readinessItems, setReadinessItems] = useState(defaultReadinessItems);
  const [releaseGateStatus] = useState<"PENDING" | "PASS" | "CONDITIONAL_PASS" | "FAIL">("PENDING");

  const handleBobPromptDetected = (prompt: string) => {
    setBobPrompt(prompt);
    // Update readiness when Bob prompt is generated
    setReadinessItems((prev) =>
      prev.map(([label, status]) =>
        label === "Bob prompt ready" ? [label, true] : [label, status]
      )
    );
  };

  const handleExportMarkdown = () => {
    // Generate enhanced markdown export of current delivery state
    const timestamp = new Date().toISOString();
    const formattedDate = new Date().toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short'
    });
    
    const markdown = `# ADA Delivery Report

**Generated:** ${formattedDate}
**Workspace ID:** ${MVP_WORKSPACE_ID}
**Timestamp:** ${timestamp}

---

## Current Mission

**Title:** ${currentMission.title}

**Description:**
${currentMission.description}

---

## Bob Prompt Preview

${bobPrompt ? `\`\`\`
${bobPrompt}
\`\`\`` : '_No Bob prompt generated yet._'}

---

## Readiness Checklist

${readinessItems
  .map(([label, status]) => `- [${status ? "x" : " "}] ${label}`)
  .join("\n")}

---

## Release Gate Status

**Current Status:** ${releaseGateStatus}

**Release Policy:**
Commit and push only after:
- QA acceptance (PASS or CONDITIONAL PASS)
- Evidence export complete
- Human lead approval

---

## Notes

This report captures the current state of the ADA delivery workflow.
Review all sections before proceeding to commit/push.

---

*Generated by ADA — AI Delivery Architect*
*IBM Bob Hackathon MVP*
`;

    // Create and download markdown file
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const filename = `ada-delivery-report-${currentMission.title.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.md`;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // Update readiness
    setReadinessItems((prev) =>
      prev.map(([label, status]) =>
        label === "Evidence exported" ? [label, true] : [label, status]
      )
    );
  };

  return (
    <main className="min-h-screen bg-neutral-950 text-neutral-100">
      <header className="border-b border-neutral-800 bg-neutral-950/95 px-6 py-5">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-6">
          <div>
            <p className="font-mono text-xs uppercase tracking-[0.3em] text-blue-400">
              IBM Bob Workflow Companion
            </p>
            <h1 className="mt-2 text-4xl font-black tracking-tight md:text-6xl">
              ADA — AI Delivery Architect
            </h1>
            <p className="mt-3 max-w-2xl text-sm text-neutral-400">
              Bob builds. Ada orchestrates and reviews. You lead.
            </p>
          </div>
          <div className="hidden border border-blue-500 bg-blue-500/10 px-4 py-3 font-mono text-xs uppercase tracking-[0.2em] text-blue-300 md:block">
            Two AIs are better than one
          </div>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-4 px-6 py-6 lg:grid-cols-[260px_1fr_360px]">
        <WorkflowSidebar />

        <ChatPanel
          workspaceId={MVP_WORKSPACE_ID}
          onBobPromptDetected={handleBobPromptDetected}
        />

        <ContextPanel
          currentMission={currentMission}
          bobPrompt={bobPrompt}
          readinessItems={readinessItems}
          releaseGateStatus={releaseGateStatus}
          onExportMarkdown={handleExportMarkdown}
        />
      </section>
    </main>
  );
}

